name: DeployMyBlog

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - tmp

env:
  GIT_USER: github
  GIT_EMAIL: github@gmail.com
  DEPLOY_BRANCH: release

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18.17.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          # cp _config.fluid.yml themes/concise/_config.yml

          mkdir -p public
          git worktree add docs $DEPLOY_BRANCH

      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install --force
          nvm use ${{ matrix.node_version }}
          echo "##$$%%"

      - name: Deploy
        run: |
          CurrentTimestampe=`date '+%Y%m%d_%H%M%S'`
          cd docs
          git checkout -b $CurrentTimestampe v0
          cd ..
          hexo clean
          hexo d
          cp -rf public/* doc
          cd docs
          git add .
          git commit -m "Github Action Trigger in $CurrentTimestampe"
          # git checkout release
          # git push github release
          git rebase -i release $CurrentTimestampe
          git checkout release
          git push github release

          cd ..
          git worktree remove docs
